name = "flappy-ranking"
main = "./build/worker.mjs"
compatibility_date = "2025-03-21"

[build]
command = "make build"

[[d1_databases]]
binding = "FlappyDB"
database_name = "flappy-ranking"
database_id = "dummy-database-id"
preview_database_id = "flappy-ranking-preview"

# [[routes]]
# pattern = "*"
# script = "server/workers.go"
# [routes.headers]
# Access-Control-Allow-Origin = "*"
# Access-Control-Allow-Methods = "GET, POST, OPTIONS"
# Access-Control-Allow-Headers = "Content-Type"
